version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine

  seq:
    image: datalust/seq:latest

  zipkin:
    image: openzipkin/zipkin-slim

  basket-api:
    image: ${REGISTRY:-wjkhappy14}/basket.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    depends_on:
      - identity-api
      - redis

  basket-api-dapr:
    image: "daprio/daprd:1.5.1"
    network_mode: "service:basket-api"
    depends_on:
      - basket-api

  blazor-client:
    image: ${REGISTRY:-wjkhappy14}/blazor.client:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/BlazorClient.Host/Dockerfile

  catalog-api:
    image: ${REGISTRY:-wjkhappy14}/catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - mysql-db

  catalog-api-dapr:
    image: "daprio/daprd:1.5.1"
    network_mode: "service:catalog-api"
    depends_on:
      - catalog-api

  identity-api:
    image: ${REGISTRY:-wjkhappy14}/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    depends_on:
      - mysql-db

  ordering-api:
    image: ${REGISTRY:-wjkhappy14}/ordering.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - mysql-db

  ordering-api-dapr:
    image: "daprio/daprd:1.5.1"
    network_mode: "service:ordering-api"
    depends_on:
      - ordering-api

  payment-api:
    image: ${REGISTRY:-wjkhappy14}/payment.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile

  payment-api-dapr:
    image: "daprio/daprd:1.5.1"
    network_mode: "service:payment-api"
    depends_on:
      - payment-api

  webshoppingagg:
    image: ${REGISTRY:-wjkhappy14}/webshoppingagg:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Aggregators/Web.Shopping.HttpAggregator/Dockerfile
    depends_on:
      - basket-api
      - catalog-api
      - identity-api
      - ordering-api
      - mysql-db

  webshoppingagg-dapr:
    image: "daprio/daprd:1.5.1"
    network_mode: "service:webshoppingagg"
    depends_on:
      - webshoppingagg

  webshoppingapigw:
    image: envoyproxy/envoy:v1.14.2

  webshoppingapigw-dapr:
    image: "daprio/daprd:1.5.1"
    network_mode: "service:webshoppingapigw"
    depends_on:
      - webshoppingapigw

  webstatus:
    image: xabarilcoding/healthchecksui:5.0.0
  
  mysql-db:
    image: mysql

  ubuntu:
    image: ubuntu
    restart: always

  dapr-placement:
    image: "daprio/dapr:1.5.1"