apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://admin:zxcvbnm@rabbitmq:5672"
    #amqps://nyipabyg:FUcLCU1Ur-giK6WBtiAiwDJPBJGmB1Ru@gerbil.rmq.cloudamqp.com/nyipabyg