kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq
  template:
    metadata:
      labels:
        app: eshop
        service: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_DEFAULT_PASS
          value: zxcvbnm
        ports:
          - name: http
            containerPort: 5672
            protocol: TCP
          - name: http-admin
            containerPort: 15672
            protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 5672
      targetPort: 5672
      nodePort: 32672
      protocol: TCP
      name: rabbitmq
    - port: 15672
      targetPort: 15672
      nodePort: 31672
      protocol: TCP
      name: rabbitmq-admin
  selector:
    service: rabbitmq
